// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fit_nonprobsvy_rcpp
arma::vec fit_nonprobsvy_rcpp(arma::mat X, arma::vec R, arma::vec weights, std::string method_selection, std::string h, double lambda, int maxit, double eps, bool warn);
RcppExport SEXP _nonprobsvy_fit_nonprobsvy_rcpp(SEXP XSEXP, SEXP RSEXP, SEXP weightsSEXP, SEXP method_selectionSEXP, SEXP hSEXP, SEXP lambdaSEXP, SEXP maxitSEXP, SEXP epsSEXP, SEXP warnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< std::string >::type method_selection(method_selectionSEXP);
    Rcpp::traits::input_parameter< std::string >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type warn(warnSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_nonprobsvy_rcpp(X, R, weights, method_selection, h, lambda, maxit, eps, warn));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nonprobsvy_fit_nonprobsvy_rcpp", (DL_FUNC) &_nonprobsvy_fit_nonprobsvy_rcpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_nonprobsvy(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
