# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_nonprobsvy_rcpp <- function(X, R, weights, method_selection, h, lambda, maxit, eps, warn = FALSE) {
    .Call('_nonprobsvy_fit_nonprobsvy_rcpp', PACKAGE = 'nonprobsvy', X, R, weights, method_selection, h, lambda, maxit, eps, warn)
}

